### PR TITLE
using backpacks in missions

### PR DESCRIPTION
**Pull request by tylers-dev**
Backpacks weren't being loaded into missions, this should fix it. Also
since the UAV is faction specific, it only seems fair to always provide
a bag and terminal to each faction. Unless there is already some convert
UAV to player's faction script.

### CODE REVIEW

**Comment by codexGW** [comment]
Nicely done. I was lazy and didn't even test it.

Yeah when you assemble a quadcopter it automatically goes to whatever team
you're on when you assembled it. Whatever side the backpack is on doesn't
matter.

**Comment by AgentRev** [comment]
preventing UAV disassembly was not intended, it was only meant for static guns; removing it is not the right approach

**Comment by codexGW** [comment]
Yeah I'll make sure we add a check for just uavs and remote designators.
I'm guessing this is because of the createvehicle filter?

**Comment by AgentRev** [comment]
Yes, and also because it bypasses object locking.

**Comment by biabock** [comment]
just curious
maybe this https://github.com/biabock/ArmA3_Wasteland.Tanoa/commit/3cb4eb891c125e028a51e5225b3b8133c51a5861 should be the "right way"?

**Comment by AgentRev** [comment]
I pushed a fix 15 mins ago.

@biabock: that commit has no effect on anything whatsoever.

**Comment by codexGW** [comment]
Nice biabock, thanks. Thanks Agent for the info too.

Edit: Oh I see thanks Agent :smile:

**Pull request merged**
