### PR TITLE
fix for the disabling ambient noises addon not working

### PR DESCRIPTION
**Pull request by tylers-dev**

### CODE REVIEW

**Comment by AgentRev** [comment]
goddamnit you guys, stop allowing this, it doesn't give any FPS gain whatsoever regardless of whoever claimed that bs. It just breaks immersion and gives an unfair advantage to people who disable it.

**Comment by codexGW** [comment]
Yeah I agree, its basically a cheat and takes away from the game. It was done because after a update a few months back BIS made the ambient animals spawn a ridiculous amount around you. It has been toned down but if you go to the dry lake on Altis its still pretty bad. Before long you'll have 4+ rabbits around you, a swarm of butterflies, and a few birds. The real reason I kept it in this time is because I was too lazy to remove the button in player menu and reorganize the other buttons. It would take me like an hour because I'm horrible at messing with the GUI's

**Comment by AgentRev** [comment]
I don't see how is this related... the rabbits don't make any noise. It's possible to have an animal cleanup instead.

**Comment by codexGW** [comment]
I don't use it for ambient noises. It was a unfortunate side affect off the command. I don't know why but the animals bother me and I'm guessing a few others because that is what this script was made for. Tyler plus a lot of others probably not. I have gotten a lot of reports about this but none about the parking icons... lol. People get used to certain ways of game play and god help us if we change that. If you can clean up the animals a bit that would be nice and it will give me cause and support to remove this.

**Comment by tylers-dev** [comment]
I support the 'effects' toggle because I think playablity is usually preferred over immersion. I agree it's unfortunate that when you provide options to playablity advantages, you often force all players to use it or fall competitively. However, more immersion usually increases difficulty. If everyone has to hear ambient noise than less people are hearing footsteps or vehicles in the distance, which means less chances for interaction. It's a debate we have all the time. Trying to keep a popular balance of playablity without sacrificing too much of what makes Arma. I don't necessarily care if we get rid of it. But I've heard many many people say that this 'effects' toggle is one of the reasons they play on Armory. People want to find action more than they want to listen to fucking bird and wind noises. :)

**Comment by codexGW** [comment]
I think a lot of the people that use it also have their ambient sound turned up high (hear those foot steps better). So they are more sensitive to the ambient sounds.

**Comment by AgentRev** [comment]
Yes, that's exactly the problem, and it must be dealt with (look up "Asus Sonic Radar"). I don't want to disable env just to be on par with others, and I don't want someone to hear me sneak behind him in the middle of the jungle. It's not frickin Counter Strike. It's a literally a developer option for debugging; giving it to players is ridiculous. The reason behind its addition to Wasteland is no longer valid.

**Comment by codexGW** [comment]
It's still valid, just not as bad. The animal spawns are still pretty overkill. Can you add a quick animal cleanup? I do think its worth the time if you can do it quickly and with out much hassle. BTW I know they are client only.

**Comment by tylers-dev** [comment]
Does enableEnvironment actually have any effect on animals?
https://community.bistudio.com/wiki/enableEnvironment
It says (ambient life + sound) but I think that means the bugs and butterflies you see flying around you. Not rabbits and snakes. Do you know Agent?

**Comment by AgentRev** [comment]
I have no idea about its effect on animals and stuff, I believed it was only for sound until today.

**Comment by codexGW** [comment]
Dude of course it does. That's why the script was made in the first place. I think I would have notice during the implementation and testing. What do you think, I just make up stories lol.

**Comment by tylers-dev** [comment]
It's a pretty easy test, go find a rabbit. And toggle the button, does the rabbit disappear? I still see animal life when it's off.

**Comment by codexGW** [comment]
Yeah and that's what was done LOTS of times by me and the person who made it and the people on the A3W forum topic that used it.

**Comment by codexGW** [comment]
This is all I could find. The search on the A3W forum isn't that good.

http://www.a3armory.com/forum/thread-77.html?highlight=invasion

**Comment by AgentRev** [comment]
not tested, but I think you could put this in playerHud.sqf:

```
{
    _a = agent _x;

    if ({_a isKindOf _x} count ["Rabbit_F","Snake_random_F"] > 0) then // maybe also "Bird"
    {
        deleteVehicle _a;
    };
} forEach agents;
```

**Comment by tylers-dev** [comment]
Wait aren't animals objects of the server? How does this work? Each player would delete the agent that renders that object to their client? So they would still exist, just nobody would see them? Would that actually help FPS? That call along happening every sec in the playerHud would seem to use more processing than what it's deleting.

**Comment by codexGW** [comment]
Yeah I was thinking something that runs ever 30 seconds so they don't get removed all the time just before they start congregating once you stay in one spot. If you just use "Animals" that might be easier too. How would I do that?

**Comment by codexGW** [comment]
Screw it, this is dumb. Lets just remove it and leave up to BIS to one day fix.

**Comment by AgentRev** [comment]
I looked it up and no one seems to agree on whether or not animals are client or server side. n00bs.

**Comment by tylers-dev** [comment]
Really? Don't they have to be server side if everyone sees the same animal? I'm pretty sure the little fuckers open doors, and like if I shoot one, the buddy next to me will watch it die.

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/41c0a067777810d5e02cb89114d298f1890064ee

**Comment by codexGW** [comment]
1.66.140166 new PROFILING branch
+ EnableEnvironment improvement (possible to disable ambient life and environmental sounds separately)
https://forums.bistudio.com/topic/160288-arma-3-stable-server-166-performance-binary-feedback/?page=78#comment-3145555

I guess its still a issue. Or at least enough to spend the time to do this and put it in perf branch not dev.

**Comment by AgentRev** [comment]
Unrelated - please check your steam messages asap

**Pull request merged**
